config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => "/api-docs"
  mount Rswag::Api::Engine => "/api-docs"

  root to: redirect("/imports")

  get "imports", to: "imports#index", as: "imports_index"
  get "imports/new"
  get "imports/:import_history_id", to: "imports#import_history", as: "imports_import_history"
  get "imports/:import_history_id/properties", to: "imports#import_history_properties", as: "imports_import_history_properties"
  get "imports/:import_history_id/error_file", to: "imports#download_error_file", as: "imports_download_error_file"
  get "imports/:import_history_id/original_file", to: "imports#download_original_file", as: "imports_download_original_file"
  post "imports/upload"

  get "properties", to: "properties#index", as: "properties_index"
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  protect_from_forgery with: :null_session, if: -> { request.format.json? }

  DEFAULT_IMPORTS_PER_PAGE = 10
  DEFAULT_IMPORTS_PROPERTIES_PER_PAGE = 10

  # GET /imports
  # GET /imports.json
  def index
    param!(:page, Integer, default: 1)
    param!(:per, Integer, default: DEFAULT_IMPORTS_PER_PAGE)

    page = params[:page]
    per = params[:per]

    @import_histories = ImportHistory
      .all
      .with_attached_imported_file
      .with_attached_imported_file_with_errors
      .order(imported_at: :desc).page(page).per(per).decorate

    respond_to do |format|
      format.html
      format.json { render json: @import_histories }
    end
  end

  # GET /imports/new
  def new
  end

  # GET /imports/:import_history_id/properties
  # GET /imports/:import_history_id/properties.json
  def import_history_properties
    param!(:import_history_id, String, required: true)
    param!(:page, Integer, default: 1)
    param!(:per, Integer, default: DEFAULT_IMPORTS_PROPERTIES_PER_PAGE)

    page = params[:page]
    per = params[:per]

    @import_history = ImportHistory.find(params[:import_history_id]).decorate
    @properties = @import_history.properties.order(external_id: :asc).page(page).per(per).decorate

    respond_to do |format|
      format.html
      format.json { render json: {total_count: @properties.total_count, total_pages: @properties.total_pages, properties: @properties} }
    end
  end

  # GET /imports/import_history.json
  def import_history
    param!(:import_history_id, String, required: true)

    @import_history = ImportHistory.find(params[:import_history_id]).decorate

    render json: @import_history
  end

  # POST /imports/upload
  # POST /imports/upload.json
  def upload
    param!(:file, ActionDispatch::Http::UploadedFile, required: true)

    @import_history = Imports::UploadService.call(file: params[:file]).decorate

    respond_to do |format|
      format.html { redirect_to imports_index_path }
      format.json { render json: @import_history.as_json(only: :id), status: :ok }
    end
  end

  # GET /imports/:import_history_id/download_original_file
  def download_original_file
    param!(:import_history_id, String, required: true)

    import_history = ImportHistory.find(params[:import_history_id]).decorate

    send_data(import_history.imported_file.download, filename: "import_#{import_history.id}.csv", type: "text/csv")
  end

  # GET /imports/:import_history_id/download_error_file
  def download_error_file
    param!(:import_history_id, String, required: true)

    import_history = ImportHistory.find(params[:import_history_id]).decorate

    send_data(import_history.imported_file_with_errors.download, filename: "import_errors_#{import_history.id}.csv", type: "text/csv")
  end
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/views/imports/import_history_properties.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <%= render "common/back" %>

  <div class="mt-4 sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-base font-semibold leading-6 text-gray-900">Properties of import #<%= @import_history.id %> (<%= @import_history.imported_properties_count %> properties)</h1>
      <p class="mt-2 text-sm text-gray-700">Imported on <%= @import_history.imported_at %>.</p>
    </div>
  </div>
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table id="properties" class="min-w-full divide-y divide-gray-300">
          <thead>
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">External ID</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Name</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Full Address</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Area</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Rent</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Property Type</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200">
            <% @properties.each do |property| %>
              <tr>
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= property.external_id %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= property.name %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= property.full_address %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= property.formatted_area_square_meters %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= property.formatted_rent %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= property.formatted_property_type %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <div class="flex justify-center mt-8">
          <%= paginate @properties %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/imports/index.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-base font-semibold leading-6 text-gray-900">Import History</h1>
      <p class="mt-2 text-sm text-gray-700">All the imports that have been done.</p>
    </div>
    <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
      <%= link_to "Import properties", imports_new_path, class: "block rounded-md bg-pink-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-pink-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-pink-600" %>
    </div>
  </div>

  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-300" id="import-histories">
          <thead>
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Import Code</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Imported Properties Count</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Imported At</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Status</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Details</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200">
            <% @import_histories.each do |import_history| %>
              <tr>
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= import_history.id %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= import_history.imported_properties_count %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= import_history.imported_at %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                  <span class="<%= "inline-flex items-center rounded-md bg-#{import_history.import_status_color}-50 px-2 py-1 text-xs font-medium text-#{import_history.import_status_color}-700 ring-1 ring-inset ring-#{import_history.import_status_color}-600/20" %>">
                    <%= import_history.formatted_import_status %>
                  </span>
                </td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500 space-y-2">
                  <span class="text-red-600 font-semibold"><%= import_history.formatted_import_failure_type %></span>

                  <% if import_history.imported_file_with_errors.attached? %>
                    <div>
                      <%= link_to imports_download_error_file_path(import_history_id: import_history.id), class: "inline-flex rounded-md bg-pink-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-pink-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-pink-600" do %>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
                        </svg>
                        <span class="ml-2">Error report</span>
                      <% end %>
                    </div>
                  <% end %>
                  <% if import_history.imported_file.attached? %>
                    <div>
                      <%= link_to imports_download_original_file_path(import_history_id: import_history.id), class: "inline-flex rounded-md bg-pink-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-pink-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-pink-600" do %>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
                        </svg>
                        <span class="ml-2">Original file</span>
                      <% end %>
                    </div>
                  <% end %>
                </td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
                  <% if import_history.import_status_completed? %>
                    <%= link_to imports_import_history_properties_path(import_history_id: import_history.id), class: "relative inline-flex items-center px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0 text-pink-600 hover:text-pink-900" do %>
                      <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
                      </svg>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <div class="flex justify-center mt-8">
          <%= paginate @import_histories %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/imports/new.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <%= render "common/back" %>

  <div class="mt-4 sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-base font-semibold leading-6 text-gray-900">Import properties</h1>
      <p class="mt-2 text-sm text-gray-700">Upload your CSV file and import properties.</p>
    </div>
  </div>
  <div class="mt-8 flow-root">
    <%= form_tag imports_upload_path, multipart: true, data: { controller: "file-upload" } do %>
      <div class="block text-sm font-medium leading-6 text-gray-900">CSV File</div>
      <div class="mt-2 flex justify-center rounded-lg border border-dashed border-gray-900/25 px-6 py-10">
        <div class="text-center">
          <svg data-file-upload-target="placeholder" class="mx-auto h-12 w-12 text-gray-300" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M1.5 6a2.25 2.25 0 012.25-2.25h16.5A2.25 2.25 0 0122.5 6v12a2.25 2.25 0 01-2.25 2.25H3.75A2.25 2.25 0 011.5 18V6zM3 16.06V18c0 .414.336.75.75.75h16.5A.75.75 0 0021 18v-1.94l-2.69-2.689a1.5 1.5 0 00-2.12 0l-.88.879.97.97a.75.75 0 11-1.06 1.06l-5.16-5.159a1.5 1.5 0 00-2.12 0L3 16.061zm10.125-7.81a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0z" clip-rule="evenodd" />
          </svg>
          <div data-file-upload-target="filename" class="text-xl font-semibold text-gray-400"></div>
          <div class="mt-4 flex justify-center text-sm leading-6 text-gray-600">
            <label for="file" class="relative cursor-pointer rounded-md bg-white font-semibold text-pink-600 hover:text-pink-500">
              <span>Upload a file</span>
              <%= file_field_tag :file, accept: ".csv", class: "sr-only", data: { file_upload_target: "input", action: "change->file-upload#onInputChange" } %>
            </label>
          </div>
          <p class="text-xs leading-5 text-gray-600">CSV up to 20MB</p>
        </div>
      </div>

      <div class="mt-4 flex justify-center">
        <%= submit_tag "Import", class: "disabled:opacity-50 cursor-pointer w-48 rounded-md bg-pink-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-pink-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-pink-600", disabled: true, data: { file_upload_target: "submit" } %>
      </div>
    <% end %>
  </div>
</div>

app/views/imports/show.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-base font-semibold leading-6 text-gray-900">Properties of import #<%= @import_history.id %> (<%= @import_history.imported_at %>)</h1>
      <p class="mt-2 text-sm text-gray-700">All the properties that have been imported.</p>
    </div>
  </div>
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table id="properties" class="min-w-full divide-y divide-gray-300">
          <thead>
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">External ID</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Name</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Full Address</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Area (in m²)</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Rent</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Property Type</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200">
            <% @properties.each do |property| %>
              <tr>
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= property.external_id %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= property.name %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= property.full_address %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= property.area_square_meters %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= property.rent %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= property.property_type %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>