config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => "/api-docs"
  mount Rswag::Api::Engine => "/api-docs"

  root to: redirect("/imports")

  get "imports", to: "imports#index", as: "imports_index"
  get "imports/new"
  get "imports/:import_history_id", to: "imports#import_history", as: "imports_import_history"
  get "imports/:import_history_id/properties", to: "imports#import_history_properties", as: "imports_import_history_properties"
  get "imports/:import_history_id/error_file", to: "imports#download_error_file", as: "imports_download_error_file"
  get "imports/:import_history_id/original_file", to: "imports#download_original_file", as: "imports_download_original_file"
  post "imports/upload"

  get "properties", to: "properties#index", as: "properties_index"
end

app/views/layouts/_header.html.erb
<nav class="border-b border-gray-200 bg-white">
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="flex h-16 justify-between">
      <div class="flex">
        <%= link_to imports_index_path, class: "flex flex-shrink-0 items-center" do %>
          <img class="block h-8 w-auto lg:hidden" src="https://tailwindui.com/plus/img/logos/mark.svg?color=pink&shade=600" alt="Spacely">
          <img class="hidden h-8 w-auto lg:block" src="https://tailwindui.com/plus/img/logos/mark.svg?color=pink&shade=600" alt="Spacely">
        <% end %>

        <div class="hidden sm:-my-px sm:ml-6 sm:flex sm:space-x-8">
          <!-- Current: "border-pink-500 text-gray-900", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" -->
          <%= link_to "Imports", imports_index_path, class: "inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium #{current_page?(imports_index_path) ? "border-pink-500 text-gray-900" : "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700"}" %>
          <%= link_to "Properties", properties_index_path, class: "inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium #{current_page?(properties_index_path) ? "border-pink-500 text-gray-900" : "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700"}" %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpacelyCsvImporter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="min-h-full">
      <%= render "layouts/header" %>

      <div class="py-10 mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
        <%= yield %>
      </div>
    </main>
  </body>
</html>